Repository AlanMorel/MapleServer2, pull requests merged in 2021-09, with the labels that each got.

#358 Fix: Improve the load of all Metadata.
  MapleServer2/Data/Static/AnimationStorage.cs
  MapleServer2/Data/Static/BeautyMetadataStorage.cs
  MapleServer2/Data/Static/ChatStickerMetadataStorage.cs
  MapleServer2/Data/Static/ColorPaletteMetadataStorage.cs
  MapleServer2/Data/Static/DefaultItemsMetadataStorage.cs
  MapleServer2/Data/Static/DungeonMetadataStorage.cs
  MapleServer2/Data/Static/ExpMetadataStorage.cs
  MapleServer2/Data/Static/FishMetadataStorage.cs
  MapleServer2/Data/Static/FishingRodMetadataStorage.cs
  MapleServer2/Data/Static/FishingSpotMetadataStorage.cs
  MapleServer2/Data/Static/FurnishingShopMetadataStorage.cs
  MapleServer2/Data/Static/GachaMetadataStorage.cs
  MapleServer2/Data/Static/GuildBuffMetadataStorage.cs
  MapleServer2/Data/Static/GuildContributionMetadataStorage.cs
  MapleServer2/Data/Static/GuildHouseMetadataStorage.cs
  MapleServer2/Data/Static/GuildPropertyMetadataStorage.cs
  MapleServer2/Data/Static/GuildServiceMetadataStorage.cs
  MapleServer2/Data/Static/HomeTemplateMetadataStorage.cs
  MapleServer2/Data/Static/InsigniaMetadataStorage.cs
  MapleServer2/Data/Static/InstrumentCategoryInfoMetadataStorage.cs
  MapleServer2/Data/Static/InstrumentInfoMetadataStorage.cs
  MapleServer2/Data/Static/ItemExchangeScrollMetadataStorage.cs
  MapleServer2/Data/Static/ItemExtractionMetadataStorage.cs
  MapleServer2/Data/Static/ItemGemstoneUpgradeMetadataStorage.cs
  MapleServer2/Data/Static/ItemMetadataStorage.cs
  MapleServer2/Data/Static/ItemOptionConstantMetadataStorage.cs
  MapleServer2/Data/Static/ItemOptionRandomMetadataStorage.cs
  MapleServer2/Data/Static/ItemOptionRangeStorage.cs
  MapleServer2/Data/Static/ItemOptionStaticMetadataStorage.cs
  MapleServer2/Data/Static/ItemSocketMetadataStorage.cs
  MapleServer2/Data/Static/JobMetadataStorage.cs
  MapleServer2/Data/Static/MapEntityStorage.cs
  MapleServer2/Data/Static/MapMetadataStorage.cs
  MapleServer2/Data/Static/MasteryFactorMetadataStorage.cs
  MapleServer2/Data/Static/MasteryMetadataStorage.cs
  MapleServer2/Data/Static/MasteryUGCHousingMetadataStorage.cs
  MapleServer2/Data/Static/NpcMetadataStorage.cs
  MapleServer2/Data/Static/OXQuizMetadataStorage.cs
  MapleServer2/Data/Static/PremiumClubDailyBenefitMetadataStorage.cs
  MapleServer2/Data/Static/PremiumClubPackageMetadataStorage.cs
  MapleServer2/Data/Static/PrestigeMetadataStorage.cs
  MapleServer2/Data/Static/QuestMetadataStorage.cs
  MapleServer2/Data/Static/RecipeMetadataStorage.cs
  MapleServer2/Data/Static/RewardContentMetadataStorage.cs
  MapleServer2/Data/Static/ScriptMetadataStorage.cs
  MapleServer2/Data/Static/SkillMetadataStorage.cs
  MapleServer2/Data/Static/TrophyMetadataStorage.cs
  MapleServer2/Data/Static/UGCMapMetadataStorage.cs
  MapleServer2/Data/Static/WorldMapGraphStorage.cs
  MapleServer2/Extensions/StringExtensions.cs
  MapleServer2/MapleServer.cs
  MapleServer2/Tools/CommandManager.cs
  MapleServer2/Tools/MetadataHelper.cs
  MapleServer2/Tools/MobAIManager.cs
Labels: enhancement

#360 Fix: fixed shop UID on seeding
  MapleServer2/Database/Seeding/ShopsSeeding.sql
Labels: hotfix

#361 Fix: Events
  MapleServer2/PacketHandlers/Game/BeautyHandler.cs
  MapleServer2/PacketHandlers/Game/GlobalPortalHandler.cs
  MapleServer2/Types/Player.cs
Labels: hotfix

#362 Fix: Fishing
  MapleServer2/PacketHandlers/Game/FishingHandler.cs
Labels: hotfix

#364 Cleanup
  MapleServer2/Commands/Core/InGameCommand.cs
  MapleServer2/MapleServer.cs
  MapleServer2/PacketHandlers/Game/ItemEquipHandler.cs
  MapleServer2/PacketHandlers/Game/TriggerHandler.cs
  MapleServer2/Packets/Helpers/ItemPacketHelper.cs
  MapleServer2/Types/ItemStats.cs
Labels: Cleanup

#363 Fix: Trophies
  GameDataParser/Hash/ms2-trophy-metadata-hash
  GameDataParser/Parsers/TrophyParser.cs
  Maple2Storage/Enums/RewardType.cs
  Maple2Storage/Types/Metadata/TrophyMetadata.cs
  MapleServer2/Data/Static/TrophyMetadataStorage.cs
  MapleServer2/Database/Classes/DatabaseCharacter.cs
  MapleServer2/Database/Classes/DatabaseTrophy.cs
  MapleServer2/Database/SQL/Database.sql
  MapleServer2/PacketHandlers/Game/StateHandler.cs
  MapleServer2/PacketHandlers/Game/TrophyHandler.cs
  MapleServer2/Packets/TrophyPacket.cs
  MapleServer2/Types/Player.cs
  MapleServer2/Types/Trophy.cs
Labels: enhancement

#367 Feat: character info handler
  MapleServer2/Database/Classes/DatabaseInventory.cs
  MapleServer2/PacketHandlers/Game/CharacterInfoHandler.cs
  MapleServer2/Packets/CharacterInfoPacket.cs
  MapleServer2/Packets/CharacterListPacket.cs
  MapleServer2/Packets/FieldPacket.cs
Labels: enhancement

#368 Fix: Casting & sync skills
  GameDataParser/Hash/ms2-skill-metadata-hash
  GameDataParser/Parsers/SkillParser.cs
  Maple2Storage/Types/Metadata/SkillMetadata.cs
  MapleServer2/Enums/SkillType.cs
  MapleServer2/PacketHandlers/Game/SkillHandler.cs
  MapleServer2/Packets/Helpers/SyncStateHelper.cs
  MapleServer2/Packets/SkillDamagePacket.cs
  MapleServer2/Packets/SkillSyncPacket.cs
  MapleServer2/Packets/SkillUsePacket.cs
  MapleServer2/Servers/Game/FieldManager.cs
  MapleServer2/Types/DamageHandler.cs
  MapleServer2/Types/Player.cs
  MapleServer2/Types/RegionSkillHandler.cs
  MapleServer2/Types/SkillCast.cs
  MapleServer2/Types/StatusHandler.cs
  MapleServer2/Types/SyncState.cs
Labels: enhancement, done

#371 Fix: master
  MapleServer2/PacketHandlers/Game/ItemRepackageHandler.cs
Labels: hotfix

#373 Cleanup: Moving managers to its own folder
  MapleServer2/Commands/Game/InfoCommands.cs
  MapleServer2/Managers/BuddyManager.cs
  MapleServer2/Managers/ClubManager.cs
  MapleServer2/Managers/CommandManager.cs
  MapleServer2/Managers/DungeonManager.cs
  MapleServer2/Managers/FieldManager.cs
  MapleServer2/Managers/GlobalEventManager.cs
  MapleServer2/Managers/GroupChatManager.cs
  MapleServer2/Managers/GuildManager.cs
  MapleServer2/Managers/HomeManager.cs
  MapleServer2/Managers/HongBaoManager.cs
  MapleServer2/Managers/MobAIManager.cs
  MapleServer2/Managers/PartyManager.cs
  MapleServer2/MapleServer.cs
  MapleServer2/PacketHandlers/Game/BuddyHandler.cs
  MapleServer2/PacketHandlers/Game/RequestCubeHandler.cs
  MapleServer2/PacketHandlers/Game/RideHandler.cs
  MapleServer2/PacketHandlers/Game/UserChatHandler.cs
  MapleServer2/Servers/Game/GameServer.cs
  MapleServer2/Servers/Game/GameSession.cs
  MapleServer2/Tools/FieldManagerFactory.cs
  MapleServer2/Triggers/MiniGameTriggers.cs
  MapleServer2/Triggers/PlayerTriggers.cs
  MapleServer2/Triggers/TriggerConditions.cs
  MapleServer2/Triggers/TriggerContext.cs
  MapleServer2/Triggers/UITriggers.cs
  MapleServer2/Types/Mob.cs
Labels: Cleanup

#374 Fix: FallDamageHandler missing packet send
  MapleServer2/PacketHandlers/Game/FallDamageHandler.cs
Labels: hotfix

#378 Fix: SkillParser & RegionSkills
  GameDataParser/Hash/ms2-skill-metadata-hash
  GameDataParser/Parsers/SkillParser.cs
  Maple2Storage/Types/Metadata/SkillMetadata.cs
  MapleServer2/Commands/Game/PlayerCommands.cs
  MapleServer2/Data/Static/SkillMetadataStorage.cs
  MapleServer2/Database/Classes/DatabaseSkillTab.cs
  MapleServer2/Enums/SkillType.cs
  MapleServer2/PacketHandlers/Game/SkillHandler.cs
  MapleServer2/Packets/JobPacket.cs
  MapleServer2/Packets/SkillBookTreePacket.cs
  MapleServer2/Packets/SkillDamagePacket.cs
  MapleServer2/Types/RegionSkillHandler.cs
  MapleServer2/Types/SkillCast.cs
  MapleServer2/Types/SkillTab.cs
  MapleServer2/Types/Status.cs
Labels: enhancement, done, Cleanup

#379 Feat: Awakening Packet, SetJob Command
  MapleServer2/Commands/Core/CommandBase.cs
  MapleServer2/Commands/Core/CommandHelpers.cs
  MapleServer2/Commands/Game/CurrencyCommands.cs
  MapleServer2/Commands/Game/EntityCommands.cs
  MapleServer2/Commands/Game/EventCommands.cs
  MapleServer2/Commands/Game/GMCommands.cs
  MapleServer2/Commands/Game/GotoCommands.cs
  MapleServer2/Commands/Game/GuildCommands.cs
  MapleServer2/Commands/Game/InfoCommands.cs
  MapleServer2/Commands/Game/ItemCommands.cs
  MapleServer2/Commands/Game/PlayerCommands.cs
  MapleServer2/Commands/Game/QuestCommands.cs
  MapleServer2/Commands/Game/UnlockCommands.cs
  MapleServer2/Constants/Skills/SkillTreeOrdered.cs
  MapleServer2/Data/Static/SkillMetadataStorage.cs
  MapleServer2/Enums/Job.cs
  MapleServer2/PacketHandlers/Game/UserChatHandler.cs
  MapleServer2/Packets/JobPacket.cs
  MapleServer2/Types/Player.cs
Labels: enhancement

#384 Cleanup
  GameDataParser/Parsers/ItemDropParser.cs
  GameDataParser/Parsers/SkillParser.cs
  MapleServer2/Commands/Game/GMCommands.cs
  MapleServer2/Commands/Game/InfoCommands.cs
  MapleServer2/Commands/Game/PlayerCommands.cs
  MapleServer2/Enums/Job.cs
  MapleServer2/MapleServer.cs
  MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
  MapleServer2/PacketHandlers/Game/BuddyHandler.cs
  MapleServer2/PacketHandlers/Game/RequestItemUseMultipleHandler.cs
  MapleServer2/PacketHandlers/Game/RideHandler.cs
  MapleServer2/PacketHandlers/Game/UserChatHandler.cs
  MapleServer2/Packets/MushkingRoyaleSystemPacket.cs
  MapleServer2/Servers/Game/GameServer.cs
Labels: Cleanup

#380 Feat: Console Progress Bar
  GameDataParser/Files/Spinner.cs
  GameDataParser/Parsers/MapEntityParser.cs
  GameDataParser/Program.cs
  Maple2Storage/Extensions/StringExtensions.cs
  Maple2Storage/Maple2Storage.csproj
  Maple2Storage/Tools/ConsoleUtility.cs
  MapleServer2/MapleServer.cs
  MapleServer2/Network/Session.cs
  MapleServer2/Tools/MetadataHelper.cs
Labels: enhancement

#388 Fix: Async initialize metadata
  Maple2Storage/Tools/ConsoleUtility.cs
  MapleServer2/MapleServer.cs
  MapleServer2/Tools/MetadataHelper.cs
Labels: enhancement

#389 Feat: Toggle quest tracking
  MapleServer2/Database/Classes/DatabaseQuest.cs
  MapleServer2/Database/SQL/Database.sql
  MapleServer2/PacketHandlers/Game/QuestHandler.cs
  MapleServer2/Packets/QuestPacket.cs
  MapleServer2/Types/QuestStatus.cs
Labels: enhancement

#393 Fix: ReturnCoord
  MapleServer2/PacketHandlers/Game/EnterEventFieldHandler.cs
  MapleServer2/PacketHandlers/Game/GuildHandler.cs
  MapleServer2/PacketHandlers/Game/MoveFieldHandler.cs
  MapleServer2/PacketHandlers/Game/RequestHomeHandler.cs
  MapleServer2/Types/Player.cs
Labels: hotfix

#385 Fix: NpcTalkHandler
  GameDataParser/Hash/ms2-script-metadata-hash
  GameDataParser/Parsers/ScriptParser.cs
  Maple2Storage/Enums/NpcTalkMode.cs
  Maple2Storage/Maple2Storage.csproj
  Maple2Storage/Scripts/Functions/calcAirTaxiCost.lua
  Maple2Storage/Scripts/Functions/calcTaxiCost.lua
  Maple2Storage/Scripts/Npcs/11000024.lua
  Maple2Storage/Scripts/Npcs/11000025.lua
  Maple2Storage/Scripts/Npcs/11000042.lua
  Maple2Storage/Scripts/Npcs/11000106.lua
  Maple2Storage/Scripts/Npcs/11001953.lua
  Maple2Storage/Types/Metadata/ScriptMetadata.cs
  Maple2Storage/Types/Paths.cs
  MapleServer2/Commands/Game/QuestCommands.cs
  MapleServer2/Managers/ScriptManager.cs
  MapleServer2/MapleServer2.csproj
  MapleServer2/PacketHandlers/Game/BonusGameHandler.cs
  MapleServer2/PacketHandlers/Game/Helpers/QuestHelper.cs
  MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
  MapleServer2/PacketHandlers/Game/RequestTaxiHandler.cs
  MapleServer2/PacketHandlers/Game/ShopHandler.cs
  MapleServer2/Packets/BonusGamePacket.cs
  MapleServer2/Packets/NpcTalkPacket.cs
  MapleServer2/Packets/QuestPacket.cs
  MapleServer2/Tools/ScriptLoader.cs
  MapleServer2/Types/QuestStatus.cs
Labels: enhancement

#390 Commands rework
  GameDataParser/Program.cs
  MapleServer2/Commands/Core/CommandBase.cs
  MapleServer2/Commands/Core/CommandHelpers.cs
  MapleServer2/Commands/Game/CurrencyCommands.cs
  MapleServer2/Commands/Game/EntityCommands.cs
  MapleServer2/Commands/Game/EventCommands.cs
  MapleServer2/Commands/Game/GMCommands.cs
  MapleServer2/Commands/Game/GotoCommands.cs
  MapleServer2/Commands/Game/GuildCommands.cs
  MapleServer2/Commands/Game/InfoCommands.cs
  MapleServer2/Commands/Game/ItemCommands.cs
  MapleServer2/Commands/Game/PlayerCommands.cs
  MapleServer2/Commands/Game/QuestCommands.cs
  MapleServer2/Commands/Game/UnlockCommands.cs
  MapleServer2/Data/Static/SkillMetadataStorage.cs
  MapleServer2/Managers/CommandManager.cs
  MapleServer2/Network/Session.cs
Labels: enhancement

#395 Fix: Redundant code
  GameDataParser/Program.cs
Labels: hotfix

#400 Cleanup for latest .net 6 RC1
  GameDataParser/Tools/GlobalUsing.cs
  Maple2Storage/Tools/GlobalUsing.cs
  MaplePacketLib2/Tools/GlobalUsing.cs
  MapleServer2/Tools/GlobalUsing.cs
  MapleWebServer/Controllers/ProfilesController.cs
  MapleWebServer/Program.cs
  MapleWebServer/Startup.cs
  MapleWebServer/Tools/GlobalUsing.cs
Labels: Cleanup

#398 Fix: database
  MapleServer2/Database/Classes/DatabaseAccount.cs
  MapleServer2/Database/Classes/DatabaseBankInventory.cs
  MapleServer2/Database/Classes/DatabaseBanner.cs
  MapleServer2/Database/Classes/DatabaseBuddy.cs
  MapleServer2/Database/Classes/DatabaseCardReverseGame.cs
  MapleServer2/Database/Classes/DatabaseCharacter.cs
  MapleServer2/Database/Classes/DatabaseCube.cs
  MapleServer2/Database/Classes/DatabaseEvent.cs
  MapleServer2/Database/Classes/DatabaseGameOptions.cs
  MapleServer2/Database/Classes/DatabaseGuild.cs
  MapleServer2/Database/Classes/DatabaseGuildApplication.cs
  MapleServer2/Database/Classes/DatabaseGuildMember.cs
  MapleServer2/Database/Classes/DatabaseHome.cs
  MapleServer2/Database/Classes/DatabaseHomeLayout.cs
  MapleServer2/Database/Classes/DatabaseHotbar.cs
  MapleServer2/Database/Classes/DatabaseInventory.cs
  MapleServer2/Database/Classes/DatabaseItem.cs
  MapleServer2/Database/Classes/DatabaseLevels.cs
  MapleServer2/Database/Classes/DatabaseMapleopoly.cs
  MapleServer2/Database/Classes/DatabaseMeretMarket.cs
  MapleServer2/Database/Classes/DatabaseQuest.cs
  MapleServer2/Database/Classes/DatabaseShop.cs
  MapleServer2/Database/Classes/DatabaseShopItem.cs
  MapleServer2/Database/Classes/DatabaseSkillTab.cs
  MapleServer2/Database/Classes/DatabaseTrophy.cs
  MapleServer2/Database/Classes/DatabaseWallet.cs
  MapleServer2/Database/SQL/Database.sql
  MapleServer2/Database/Seeding/CardReverseGameSeeding.sql
  MapleServer2/Database/Seeding/EventsSeeding.sql
  MapleServer2/Database/Seeding/MapleopolySeeding.sql
  MapleServer2/Database/Seeding/MeretMarketSeeding.sql
  MapleServer2/Database/Seeding/ShopItemsSeeding.sql
  MapleServer2/Database/Seeding/ShopsSeeding.sql
  MapleServer2/Database/Types/Banner.cs
  MapleServer2/Database/Types/GameEvent/FieldPopupEvent.cs
  MapleServer2/Database/Types/GameEvent/MapleopolyEvent.cs
  MapleServer2/Database/Types/GameEvent/StringBoardEvent.cs
  MapleServer2/Database/Types/GameEvent/UGCMapContractSaleEvent.cs
  MapleServer2/Database/Types/GameEvent/UGCMapExtensionSaleEvent.cs
  MapleServer2/Database/Types/MeretMarketItem.cs
  MapleServer2/Database/Types/Shop.cs
  MapleServer2/Database/Types/ShopItem.cs
  MapleServer2/Tools/ScriptLoader.cs
  MapleServer2/Types/Guild/GuildMember.cs
  MapleServer2/Types/Home/HomeLayout.cs
  MapleServer2/Types/Mapleopoly.cs
Labels: enhancement

#402 Fix: transparency badge, BeautyHandler and #401
  MapleServer2/PacketHandlers/Game/BeautyHandler.cs
  MapleServer2/PacketHandlers/Game/Helpers/QuestHelper.cs
  MapleServer2/PacketHandlers/Game/NpcTalkHandler.cs
  MapleServer2/Types/Item.cs
Labels: hotfix

#403 Fix: Dismantle & ShopPacket
  MapleServer2/Packets/ShopPacket.cs
  MapleServer2/Types/DismantleInventory.cs
  MapleServer2/Types/Item.cs
Labels: hotfix

#404 Fix: Guild coin rarity
  MapleServer2/PacketHandlers/Game/GuildHandler.cs
Labels: hotfix

#406 Fix: mastery exp & interactable objects
  GameDataParser/Hash/ms2-map-entity-metadata-hash
  GameDataParser/Parsers/MapEntityParser.cs
  MapleServer2/Types/Levels.cs
Labels: hotfix

#405 Fix: profile picture not updating correctly
  MapleWebServer/Controllers/ProfilesController.cs
Labels: hotfix

#409 Feat: Skills path
  GameDataParser/Hash/ms2-magicpath-metadata-hash
  GameDataParser/Hash/ms2-skill-metadata-hash
  GameDataParser/Parsers/MagicPathParser.cs
  GameDataParser/Parsers/SkillParser.cs
  Maple2Storage/Types/Metadata/MagicPathMetadata.cs
  Maple2Storage/Types/Metadata/SkillMetadata.cs
  MapleServer2/Commands/Game/PlayerCommands.cs
  MapleServer2/Data/Static/MagicPathMetadataStorage.cs
  MapleServer2/Enums/SkillType.cs
  MapleServer2/PacketHandlers/Game/SkillHandler.cs
  MapleServer2/Packets/RegionSkillPacket.cs
  MapleServer2/Packets/SkillDamagePacket.cs
  MapleServer2/Packets/SkillUsePacket.cs
  MapleServer2/Types/RegionSkillHandler.cs
  MapleServer2/Types/SkillCast.cs
Labels: enhancement

#417 Quest condition fix & Clean up
  GameDataParser/Parsers/QuestParser.cs
  MapleServer2/Managers/FieldManager.cs
  MapleServer2/PacketHandlers/Game/Helpers/QuestHelper.cs
  MapleServer2/PacketHandlers/Game/SkillHandler.cs
Labels: hotfix

#418 Action dotnetformat
  .github/workflows/dotnet.yml
Labels: enhancement, hotfix

#420 Action dotnet-format
  .github/workflows/dotnet.yml
Labels: hotfix

#421 Feat: Daily Reset Scheduler
  MapleServer2/Database/Classes/DatabaseServer.cs
  MapleServer2/Database/DatabaseManager.cs
  MapleServer2/Database/SQL/Database.sql
  MapleServer2/MapleServer.cs
  MapleServer2/Tools/TaskScheduler.cs
Labels: enhancement

#419 Fix: Gathering
  MapleServer2/PacketHandlers/Game/InteractObjectHandler.cs
  MapleServer2/Packets/InteractObjectPacket.cs
Labels: hotfix

#426 Feat: Function Cubes (portal, life skills, interactable objects)
  GameDataParser/Hash/ms2-function-cube-metadata-hash
  GameDataParser/Parsers/FunctionCubeParser.cs
  GameDataParser/Parsers/MapEntityParser.cs
  Maple2Storage/Enums/PortalTypes.cs
  Maple2Storage/Types/Coord.cs
  Maple2Storage/Types/Metadata/FunctionCubeMetadata.cs
  Maple2Storage/Types/Metadata/MapEntityMetadata.cs
  MapleServer2/Constants/SendOp.cs
  MapleServer2/Data/Static/FunctionCubeMetadataStorage.cs
  MapleServer2/Database/Classes/DatabaseCharacter.cs
  MapleServer2/Database/Classes/DatabaseCube.cs
  MapleServer2/Database/Classes/DatabaseHome.cs
  MapleServer2/Database/SQL/Database.sql
  MapleServer2/Enums/SyncStateFlag.cs
  MapleServer2/Enums/UGCPortals.cs
  MapleServer2/Managers/FieldManager.cs
  MapleServer2/Managers/HomeManager.cs
  MapleServer2/MapleServer.cs
  MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
  MapleServer2/PacketHandlers/Game/FieldEnterHandler.cs
  MapleServer2/PacketHandlers/Game/FunctionCubeHandler.cs
  MapleServer2/PacketHandlers/Game/Helpers/GatheringHelper.cs
  MapleServer2/PacketHandlers/Game/HomeActionHandler.cs
  MapleServer2/PacketHandlers/Game/InteractObjectHandler.cs
  MapleServer2/PacketHandlers/Game/LoadUgcMapHandler.cs
  MapleServer2/PacketHandlers/Game/MoveFieldHandler.cs
  MapleServer2/PacketHandlers/Game/RequestCubeHandler.cs
  MapleServer2/PacketHandlers/Game/RequestHomeHandler.cs
  MapleServer2/Packets/FieldPacket.cs
  MapleServer2/Packets/FunctionCubePacket.cs
  MapleServer2/Packets/Helpers/SyncStateHelper.cs
  MapleServer2/Packets/HomeActionPacket.cs
  MapleServer2/Packets/UserEnvPacket.cs
  MapleServer2/Servers/Game/GameSession.cs
  MapleServer2/Tools/FieldManagerFactory.cs
  MapleServer2/Tools/InventoryController.cs
  MapleServer2/Types/Cube.cs
  MapleServer2/Types/GatheringCount.cs
  MapleServer2/Types/Item.cs
  MapleServer2/Types/Levels.cs
  MapleServer2/Types/Player.cs
  MapleServer2/Types/Portal.cs
  MapleServer2/Types/SyncState.cs
Labels: enhancement

#427 Fix: Teleporting to offline player home
  GameDataParser/Parsers/MapEntityParser.cs
  MapleServer2/Database/Classes/DatabaseCharacter.cs
  MapleServer2/Managers/FieldManager.cs
  MapleServer2/PacketHandlers/Game/FieldEnterHandler.cs
  MapleServer2/PacketHandlers/Game/MoveFieldHandler.cs
  MapleServer2/PacketHandlers/Game/RequestCubeHandler.cs
  MapleServer2/PacketHandlers/Game/RequestHomeHandler.cs
  MapleServer2/Packets/ResponseCubePacket.cs
  MapleServer2/Triggers/FieldObjectTriggers.cs
Labels: hotfix

#429 Fix: gathering
  GameDataParser/Hash/ms2-item-metadata-hash
  GameDataParser/Parsers/ItemParser.cs
  Maple2Storage/Types/Metadata/ItemMetadata.cs
  MapleServer2/Data/Static/ItemMetadataStorage.cs
  MapleServer2/PacketHandlers/Game/FunctionCubeHandler.cs
Labels: hotfix
