Repository AlanMorel/MapleServer2, pull requests merged in 2021-08, with the labels that each got.

#333 Fix: Guilds not saving correctly
  MapleServer2/Database/DatabaseManager.cs
Labels: bug

#334 Fix: Beauty crash and returning to correct map
  MapleServer2/PacketHandlers/Game/BeautyHandler.cs
Labels: bug

#332 Feat: Lua scripting
  MapleServer2/Data/Static/WorldMapGraphStorage.cs
  MapleServer2/MapleServer2.csproj
  MapleServer2/PacketHandlers/Game/RequestTaxiHandler.cs
  MapleServer2/Scripts/calcAirTaxiCost.lua
  MapleServer2/Scripts/calcTaxiCost.lua
  MapleServer2/Tools/ScriptLoader.cs
Labels: enhancement

#341 Fix: ScriptLoader file path
  MapleServer2/Tools/ScriptLoader.cs
Labels: hotfix

#342 OX Quiz and more triggers
  GameDataParser/Hash/ms2-map-entity-metadata-hash
  GameDataParser/Hash/ms2-reward-content-metadata-hash
  GameDataParser/Parsers/MapEntityParser.cs
  GameDataParser/Parsers/RewardContentParser.cs
  GameDataParser/Program.cs
  Maple2Storage/Json/OXQuizQuestions.json
  Maple2Storage/Types/Metadata/MapEntityMetadata.cs
  Maple2Storage/Types/Metadata/RewardContentMetadata.cs
  MapleServer2/Commands/Game/EventCommands.cs
  MapleServer2/Commands/Game/InfoCommands.cs
  MapleServer2/Constants/Paths.cs
  MapleServer2/Data/Static/MapEntityStorage.cs
  MapleServer2/Data/Static/OXQuizMetadataStorage.cs
  MapleServer2/Data/Static/RewardContentMetadataStorage.cs
  MapleServer2/PacketHandlers/Game/GlobalPortalHandler.cs
  MapleServer2/PacketHandlers/Game/RequestTutorialItemHandler.cs
  MapleServer2/PacketHandlers/Game/TriggerHandler.cs
  MapleServer2/Packets/CinematicPacket.cs
  MapleServer2/Packets/FieldObjectPacket.cs
  MapleServer2/Packets/GlobalPortalPacket.cs
  MapleServer2/Packets/LocalCameraPacket.cs
  MapleServer2/Packets/OneTimeEffectPacket.cs
  MapleServer2/Packets/QuizEventPacket.cs
  MapleServer2/Packets/ResultsPacket.cs
  MapleServer2/Packets/TriggerPacket.cs
  MapleServer2/Servers/Game/FieldManager.cs
  MapleServer2/Servers/Game/GameServer.cs
  MapleServer2/Servers/Game/GameSession.cs
  MapleServer2/Tools/GlobalEventManager.cs
  MapleServer2/Triggers/CameraTriggers.cs
  MapleServer2/Triggers/DungeonTriggers.cs
  MapleServer2/Triggers/FieldObjectTriggers.cs
  MapleServer2/Triggers/MiniGameTriggers.cs
  MapleServer2/Triggers/NpcTriggers.cs
  MapleServer2/Triggers/PlayerTriggers.cs
  MapleServer2/Triggers/TriggerConditions.cs
  MapleServer2/Triggers/TriggerContext.cs
  MapleServer2/Triggers/UITriggers.cs
  MapleServer2/Types/FieldState.cs
  MapleServer2/Types/GlobalEvent.cs
  MapleServer2/Types/Levels.cs
  MapleServer2/Types/OXQuizQuestion.cs
  MapleServer2/Types/Party.cs
  MapleServer2/Types/Player.cs
  MapleServer2/Types/PlayerTrigger.cs
  MapleServer2/Types/TriggerObject.cs
  MapleServer2/Types/Widget.cs
Labels: enhancement

#347 Save state on server exit
  MapleServer2/Commands/Game/UnlockCommands.cs
  MapleServer2/Database/Classes/DatabaseBanner.cs
  MapleServer2/Database/Classes/DatabaseHotbar.cs
  MapleServer2/Database/DatabaseTable.cs
  MapleServer2/MapleServer.cs
  MapleServer2/Tools/GuildManager.cs
  MapleServer2/Tools/HomeManager.cs
  MapleServer2/Triggers/MiniGameTriggers.cs
Labels: enhancement

#348 Fix: create monster trigger function
  MapleServer2/Triggers/NpcTriggers.cs
Labels: bug

#349 Fix: ActiveSkillTabId not saving correctly
  MapleServer2/Types/Player.cs
Labels: hotfix

#355 Fix: Database Shop
  MapleServer2/Database/Classes/DatabaseShop.cs
Labels: hotfix

#354 Fix: Buddies
  MapleServer2/Database/Classes/DatabaseAccount.cs
  MapleServer2/Database/Classes/DatabaseBuddy.cs
  MapleServer2/Database/Classes/DatabaseCharacter.cs
  MapleServer2/Database/Classes/DatabaseGuildMember.cs
  MapleServer2/Database/DatabaseManager.cs
  MapleServer2/Database/SQL/Database.sql
  MapleServer2/PacketHandlers/Common/ResponseKeyHandler.cs
  MapleServer2/PacketHandlers/Game/BuddyHandler.cs
  MapleServer2/PacketHandlers/Game/QuitHandler.cs
  MapleServer2/Packets/BuddyPacket.cs
  MapleServer2/Servers/Game/GameSession.cs
  MapleServer2/Tools/BuddyManager.cs
  MapleServer2/Types/Buddy.cs
  MapleServer2/Types/Player.cs
Labels: enhancement
